tiscaf: Fix for weird JVM versions
On certain JVM versions specific parts of the tiscaf library caused an
error of type 'java.lang.NoSuchMethodError: java.nio.ByteBuffer.clear'.
This commit works around the error by catching it and handling it
appropriatly.